apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: vaultresources.vault.crossplane.io
spec:
  group: vault.crossplane.io
  names:
    kind: VaultResources
    plural: vaultresources
  claimNames:
    kind: VaultResourcesClaim
    plural: vaultresourcesclaims
  versions:
    - name: v1beta1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                compositionRef:
                  type: object
                  properties:
                    name:
                      type: string
                      